//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        public int Id { get; set; }
        [Required (ErrorMessage = "Город отправителя не может быть пустым полем!")]
        [Display(Name = "Город отправителя")]
        public string SenderCity { get; set; }
        [Required(ErrorMessage = "Адрес отправителя не может быть пустым полем!")]
        [Display(Name = "Адрес отправителя")]
        public string SenderAddress { get; set; }
        [Required(ErrorMessage = "Город получателя не может быть пустым полем!")]
        [Display(Name = "Город получателя")]
        public string RecipientCity { get; set; }
        [Required(ErrorMessage = "Город отправителя не может быть пустым полем!")]
        [Display(Name = "Адрес получателя")]
        public string RecipientAddress { get; set; }
        [Required(ErrorMessage = "Должен быть задан вес отправления!")]
        [Display(Name = "Вес посылки")]
        [Range(1, 100, ErrorMessage = "Вес отправления не менее 1 и не более 100 кг!")]
        public double Weight { get; set; }
        [Required(ErrorMessage = "Дата отправления должна быть заполнена!")]
        [Display(Name = "Дата отправления")]
        public System.DateTime Date { get; set; }
    }
}
